/*
 * generated by Xtext 2.25.0
 */
package org.xtext.projects.minijava.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class MiniJavaProjectInfo extends DefaultProjectInfo {

}
