/*
 * generated by Xtext 2.25.0
 */
package org.xtext.projects.minijava.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MiniJavaWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MiniJavaWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
